### PR TITLE
pull requests

### PR DESCRIPTION
**Pull request by monica06-yan**
This is machine learning project. Is my code good?

### CODE REVIEW

**Comment by RolandAvagyan** [comment]
I like how you detailed the sequence of your steps as you work. There is nothing to change in the code itself.

**Comment by AlbertHayrapetyan2024** [comment]
You did everything right,congratulations.You don't need to change anything in the code

**Comment by monica06-yan** [comment]
> I like how you detailed the sequence of your steps as you work. There is nothing to change in the code itself.

Thank you for your contribution! I appreciate the time and effort you've put into this pull request.

**Comment by monica06-yan** [comment]
> You did everything right,congratulations.You don't need to change anything in the code

Thank you for your contribution and for supporting me.

**Pull request merged**
